name: Build and Deploy

on:
  push:
    branches:
      - main
env:
  CONTAINER_REGISTRY_URL: ${{ vars.CONTAINER_REGISTRY_URL}}
  CONTAINER_REGISTRY_REPOSITORY_NAME: ${{ vars.CONTAINER_REGISTRY_REPOSITORY_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-version: ${{ steps.set-variables.outputs.IMAGE_VERSION }}

    steps:
      
      - name: ECHO VARIABLES
        run: |
          echo "IMAGE_VERSION = $IMAGE_VERSION"
          echo "CONTAINER_REGISTRY_URL = $CONTAINER_REGISTRY_URL" 
          echo "CONTAINER_REGISTRY_REPOSITORY_NAME = $CONTAINER_REGISTRY_REPOSITORY_NAME"  

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ingestion-functions .

      - name: Log in to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Get the current date
        id: date
        run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')"
        
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.CONTAINER_REGISTRY_URL }}/custom-chat-copilot/ingestion-functions-v3:${{ steps.date.outputs.tag }}

      - name: Set image name for other jobs
        id: set-variables
        run: |
          echo "IMAGE_VERSION=${{ steps.date.outputs.tag }}" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      IMAGE_VERSION: ${{ needs.build.outputs.image-version }}
      CONTAINER_REGISTRY_URL: ${{ vars.CONTAINER_REGISTRY_URL}}
      CONTAINER_REGISTRY_REPOSITORY_NAME: ${{ vars.CONTAINER_REGISTRY_REPOSITORY_NAME }}
      INGESTION_FUNCTION_STORAGE_ACCOUNT_NAME: ${{ vars.INGESTION_FUNCTION_STORAGE_ACCOUNT_NAME }}
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ECHO VARIABLES
        run: |
          echo "IMAGE_VERSION = $IMAGE_VERSION"
          echo "CONTAINER_REGISTRY_URL = $CONTAINER_REGISTRY_URL"
          echo "CONTAINER_REGISTRY_REPOSITORY_NAME = $CONTAINER_REGISTRY_REPOSITORY_NAME"
          echo "INGESTION_FUNCTION_STORAGE_ACCOUNT_NAME = $INGESTION_FUNCTION_STORAGE_ACCOUNT_NAME"

      - name: Deploy to server       
        run: |
         az functionapp create --name ingestionservicev3 --storage-account ${{ env.INGESTION_FUNCTION_STORAGE_ACCOUNT_NAME }} --environment rutzsco-chat-copilot-demo --resource-group rutzsco-chat-copilot-demo --functions-version 4 --runtime python --image "rutzscolabcr.azurecr.io/custom-chat-copilot/ingestion-functions-v3:$IMAGE_VERSION"
